using System;
using System.Collections;
using System.Numerics;
using Autofac;
using DesignPatterns.Additional;
using DesignPatterns.Behavioral.ChainOfResponsability;
using DesignPatterns.Behavioral.Command;
using DesignPatterns.Behavioral.Interpreter;
using DesignPatterns.Behavioral.Iterator;
using DesignPatterns.Behavioral.MediatorCustom;
using DesignPatterns.Behavioral.Momento;
using DesignPatterns.Behavioral.NullObject;
using DesignPatterns.Behavioral.Observer;
using DesignPatterns.Behavioral.State;
using DesignPatterns.Behavioral.Strategy;
using DesignPatterns.Behavioral.Template;
using DesignPatterns.Behavioral.Visitor;
using DesignPatterns.Creational.Builder;
using DesignPatterns.Creational.Factories;
using DesignPatterns.Creational.Prototype;
using DesignPatterns.Creational.Prototype.Serialize;
using DesignPatterns.Creational.Singleton;
using DesignPatterns.MicrosoftDI;
using DesignPatterns.Structural.Adapter;
using DesignPatterns.Structural.Bridge;
using DesignPatterns.Structural.Composite;
using DesignPatterns.Structural.Decorator;
using DesignPatterns.Structural.Facade;
using DesignPatterns.Structural.Flyweight;
using DesignPatterns.Structural.Proxy;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.WindowsAzure.ServiceRuntime;

//await Test.Render();
//O.Render();
//L.Render();
//D.Render();
//Builder.Render();
//BuilderFluent.Render();
//BuilderFunction.Render();
//BuilderFaceted.Render();
//Factory.Render();
//FactoryPattern.Render();
//AbstractFactory.Render();
//AbstractFactoryOP.Render();
//PrototypeEx.Render();
//PrototypeCopyConstructor.Render();
//Prototype.Render();
//PrototypeInheritance.Render();
//PrototypeSerialize.Render();
//LazySingleton.Render();
//Monostate.Render();
//PerThreadSingleton.Render();
//AmbiantContext.Render();
//Adapter.Render();
//AdapterDI.Render();
//Bridge.Render();
//GeometricalShapes.Render();
//Decorator.Render();
//Decorator1.Render();
//Decorator2.Render();
//Decorator3.Render();
//Decorator4.Render();
//Decorator5.Render();
//Facade.Render();
//FlyWeight.Render();
//FlyWeight1.Render();
//ProtectionProxy.Render();
//Proxy2.Render();
//Proxy3.Render();
//COR1.Render();
//COR2.Render();
//Command.Render();
//Interpreter.Render();
//Iterator.Render();
//ChatMediator.Render();
//EventBrokerMediator.Render();
//await MediatRMediator.Render();
//Momento.Render();
//NullObject.Render();
//Observer.Render();
//WeakEventObserver.Render();
//WeakEventObserver1.Render();
//WeakEventObserver2.Render();
//BidirectionalObserver.Render();
//PropertyDependenciesObserver.Render();
//EventSubscriptionObserver.Render();
//State3.Render();
//State1.Render();
//State2.Render();
//State4.Render();
//State5.Render();
//Strategy.Render();
//Strategy11.Render();
//Strategy1.Render();
//Template.Render();
Visitor.Render();
//Visitor4.Render();
//ClassicVisitor.Render();
//Visitor2.Render();
//ClassicVisitorDLR.Render();
//AcyclicVisitor.Render();
//CQRS.Render();